/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "stm32746g_discovery_ts.h"
#include "stm32746g_discovery.h"
#include "main.h"
#include "stdio.h"
#include "stdlib.h"
#include "string.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_EDIT_0 (GUI_ID_USER + 0x01)
#define ID_BUTTON_0 (GUI_ID_USER + 0x02)
#define ID_BUTTON_1 (GUI_ID_USER + 0x03)
#define ID_BUTTON_2 (GUI_ID_USER + 0x04)
#define ID_BUTTON_3 (GUI_ID_USER + 0x05)
#define ID_BUTTON_4 (GUI_ID_USER + 0x06)
#define ID_BUTTON_5 (GUI_ID_USER + 0x07)
#define ID_BUTTON_6 (GUI_ID_USER + 0x08)
#define ID_BUTTON_7 (GUI_ID_USER + 0x09)
#define ID_BUTTON_8 (GUI_ID_USER + 0x0A)
#define ID_BUTTON_9 (GUI_ID_USER + 0x0B)
#define ID_BUTTON_10 (GUI_ID_USER + 0x0C)
#define ID_BUTTON_11 (GUI_ID_USER + 0x0D)
#define ID_TEXT_0 (GUI_ID_USER + 0x0E)
#define ID_IMAGE_0 (GUI_ID_USER + 0x0F)

#define ID_IMAGE_0_IMAGE_0 0x00

// USER START (Optionally insert additional defines)
extern  WM_HWIN CreateWindow(void);
extern  WM_HWIN Createplay(void);
extern	TS_StateTypeDef touch;
unsigned char a,b;
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
/*********************************************************************
*
*       _acImage_0, "C:\Users\JIE\Desktop\Lab3\picture\12.png", ID_IMAGE_0_IMAGE_0
*/
static const U8 _acImage_0[1058] = {
  0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A, 0x00, 0x00, 0x00, 0x0D, 0x49, 0x48, 0x44, 0x52, 0x00, 0x00, 0x00, 0x19, 0x00, 0x00, 0x00, 0x19, 0x08, 0x06, 0x00, 0x00, 0x00, 0xC4, 0xE9, 0x85, 0x63, 0x00, 0x00, 0x00, 0x01, 0x73, 0x52, 0x47, 0x42, 0x00,
  0xAE, 0xCE, 0x1C, 0xE9, 0x00, 0x00, 0x00, 0x04, 0x67, 0x41, 0x4D, 0x41, 0x00, 0x00, 0xB1, 0x8F, 0x0B, 0xFC, 0x61, 0x05, 0x00, 0x00, 0x00, 0x09, 0x70, 0x48, 0x59, 0x73, 0x00, 0x00, 0x0E, 0xC4, 0x00, 0x00, 0x0E, 0xC4, 0x01, 0x95, 0x2B, 0x0E, 0x1B, 0x00,
  0x00, 0x03, 0xB7, 0x49, 0x44, 0x41, 0x54, 0x48, 0x4B, 0x9D, 0x95, 0xBB, 0x2F, 0x6D, 0x51, 0x10, 0xC6, 0xE7, 0x6C, 0xEF, 0x67, 0x10, 0x84, 0x10, 0x05, 0x4A, 0xA2, 0xD0, 0x08, 0x41, 0xA3, 0x50, 0xEA, 0x34, 0x74, 0x42, 0x24, 0x12, 0x21, 0x0A, 0x5A, 0x94,
  0x1A, 0x51, 0xA1, 0xF1, 0xA8, 0x24, 0x0A, 0x2A, 0x15, 0x89, 0x57, 0x88, 0x57, 0x41, 0xFC, 0x01, 0x44, 0xBC, 0x22, 0x08, 0xF1, 0x7E, 0x9C, 0xBB, 0x7F, 0xE3, 0xCC, 0xBE, 0xDB, 0x71, 0xAF, 0x1B, 0xF7, 0x4B, 0x56, 0xD6, 0xDE, 0x6B, 0xCF, 0x9A, 0xEF, 0x9B,
  0x59, 0x33, 0x6B, 0x07, 0x96, 0x96, 0x96, 0x82, 0x2E, 0xE4, 0xFD, 0xFD, 0x5D, 0xBE, 0x43, 0x64, 0x64, 0xA4, 0xCC, 0xCE, 0xCE, 0xCA, 0xDE, 0xDE, 0x9E, 0x34, 0x37, 0x37, 0x4B, 0x5A, 0x5A, 0x9A, 0xAE, 0xBD, 0xBD, 0xBD, 0x09, 0xFB, 0xFF, 0x86, 0xA8, 0xA8,
  0x28, 0x71, 0xFC, 0x06, 0x81, 0x40, 0x20, 0xF4, 0xF4, 0x15, 0xA7, 0xA7, 0xA7, 0x32, 0x3A, 0x3A, 0x2A, 0x2B, 0x2B, 0x2B, 0xB2, 0xB3, 0xB3, 0x23, 0x8E, 0xE3, 0xC8, 0xCB, 0xCB, 0x8B, 0xEE, 0xC1, 0x87, 0xCD, 0xE1, 0x40, 0xBC, 0x6B, 0xEB, 0xA8, 0xC1, 0xE3,
  0xE3, 0xA3, 0xA4, 0xA7, 0xA7, 0xCB, 0xFC, 0xFC, 0xBC, 0x5C, 0x5D, 0x5D, 0xC9, 0xEB, 0xEB, 0xAB, 0xAA, 0xBC, 0xBF, 0xBF, 0x97, 0xB9, 0xB9, 0x39, 0xA9, 0xAF, 0xAF, 0x97, 0x9B, 0x9B, 0x1B, 0x79, 0x7E, 0x7E, 0x96, 0xC1, 0xC1, 0x41, 0xE9, 0xEC, 0xEC, 0x94,
  0xFD, 0xFD, 0x7D, 0x79, 0x78, 0x78, 0x50, 0xE7, 0xF1, 0xF1, 0xF1, 0xB2, 0xB0, 0xB0, 0xA0, 0xF6, 0xF8, 0xB4, 0xA1, 0x02, 0x96, 0x97, 0x97, 0xDD, 0xF9, 0x43, 0xC9, 0xEE, 0xEE, 0xAE, 0x74, 0x74, 0x74, 0x28, 0x59, 0x7B, 0x7B, 0xBB, 0x1C, 0x1D, 0x1D, 0xC9,
  0xCC, 0xCC, 0x8C, 0x9C, 0x9F, 0x9F, 0xAB, 0x6A, 0x42, 0x87, 0x84, 0x34, 0xA1, 0x30, 0x36, 0x36, 0x56, 0xF2, 0xF3, 0xF3, 0xA5, 0xB5, 0xB5, 0x55, 0xD6, 0xD6, 0xD6, 0x64, 0x72, 0x72, 0x52, 0x6A, 0x6B, 0x6B, 0xA5, 0xA7, 0xA7, 0x27, 0x14, 0xC7, 0x07, 0x3C,
  0x12, 0x58, 0x17, 0x17, 0x17, 0xA5, 0xAF, 0xAF, 0x4F, 0xA3, 0x32, 0x15, 0xA6, 0x88, 0xC8, 0xE2, 0xE2, 0xE2, 0x54, 0x29, 0x24, 0xAC, 0x41, 0x18, 0x1D, 0x1D, 0xAD, 0x8E, 0xF8, 0x9E, 0x92, 0x92, 0x22, 0x49, 0x49, 0x49, 0x32, 0x31, 0x31, 0xA1, 0x6B, 0x06,
  0x27, 0x34, 0xAB, 0x51, 0x79, 0x79, 0xB9, 0xE4, 0xE4, 0xE4, 0xE8, 0x46, 0x9C, 0xE4, 0xE5, 0xE5, 0xC9, 0xD0, 0xD0, 0x90, 0xAC, 0xAF, 0xAF, 0x4B, 0x53, 0x53, 0x93, 0x3A, 0x35, 0x42, 0x9E, 0x01, 0x33, 0x23, 0x22, 0x22, 0x42, 0xD3, 0xDC, 0xD5, 0xD5, 0xA5,
  0xEB, 0x7E, 0x78, 0x24, 0x80, 0x14, 0xE4, 0xE6, 0xE6, 0x6A, 0xEA, 0x98, 0xC7, 0xC7, 0xC7, 0xA5, 0xA5, 0xA5, 0x45, 0x8A, 0x8B, 0x8B, 0xA5, 0xBF, 0xBF, 0x5F, 0x4A, 0x4B, 0x4B, 0x95, 0x84, 0xEF, 0x7E, 0x10, 0x19, 0xC4, 0xA0, 0xAC, 0xAC, 0x4C, 0x67, 0x3F,
  0x3C, 0x12, 0x36, 0xE2, 0x60, 0x63, 0x63, 0x43, 0x95, 0xD5, 0xD5, 0xD5, 0x49, 0x75, 0x75, 0xB5, 0x3C, 0x3D, 0x3D, 0xA9, 0x13, 0xCE, 0x69, 0x64, 0x64, 0x44, 0x53, 0xC8, 0xF0, 0xC3, 0xD2, 0xC7, 0xFA, 0xF4, 0xF4, 0x74, 0x68, 0xF5, 0x37, 0x3C, 0x12, 0x2A,
  0x89, 0x43, 0xB6, 0x34, 0x24, 0x26, 0x26, 0xEA, 0xA6, 0x98, 0x98, 0x18, 0x8D, 0x90, 0x81, 0x33, 0x10, 0x1E, 0x09, 0x42, 0xF8, 0x4E, 0x61, 0x8C, 0x8D, 0x8D, 0x85, 0x56, 0x7F, 0xC3, 0x21, 0x4C, 0x0C, 0x50, 0x32, 0x3C, 0x3C, 0xAC, 0xCF, 0x38, 0xA7, 0x94,
  0x4F, 0x4E, 0x4E, 0xD4, 0x21, 0x02, 0xB0, 0x23, 0x12, 0x10, 0x1E, 0x09, 0xEF, 0x0C, 0x6C, 0xCE, 0xCE, 0xCE, 0x3E, 0x9D, 0x19, 0xD0, 0x48, 0xA8, 0xF5, 0x83, 0x83, 0x03, 0xAF, 0xB9, 0x38, 0xC4, 0xED, 0xED, 0x6D, 0x69, 0x6B, 0x6B, 0xD3, 0xD2, 0xA4, 0x3F,
  0x7A, 0x7B, 0x7B, 0xB5, 0x6A, 0xC2, 0x09, 0xFC, 0xB0, 0x6F, 0x9B, 0x9B, 0x9B, 0x2A, 0x8C, 0x02, 0xD2, 0xB5, 0xD5, 0xD5, 0xD5, 0xA0, 0xDB, 0x48, 0x41, 0xD7, 0x39, 0x16, 0x41, 0xF7, 0x83, 0xCE, 0x2E, 0x51, 0xD0, 0xED, 0x83, 0xA0, 0x9B, 0x02, 0x7D, 0xB7,
  0xC1, 0xBA, 0xFF, 0xFD, 0x4F, 0xC3, 0x4D, 0xB1, 0xFA, 0x73, 0x23, 0x0F, 0xBA, 0x6D, 0x11, 0x74, 0x2E, 0x2F, 0x2F, 0x35, 0xA7, 0xA8, 0x27, 0x0A, 0x42, 0x35, 0x05, 0x96, 0x26, 0x52, 0x69, 0xE7, 0x41, 0x3A, 0xFF, 0x05, 0x2B, 0xE9, 0xC3, 0xC3, 0xC3, 0x8F,
  0x82, 0xA2, 0x17, 0x32, 0x33, 0x33, 0xB5, 0x7B, 0x59, 0xE0, 0xF0, 0x48, 0x1B, 0x60, 0x86, 0x80, 0x61, 0x64, 0xD8, 0x30, 0xC2, 0xE1, 0x5F, 0x4F, 0x4E, 0x4E, 0xD6, 0xC6, 0xAD, 0xA8, 0xA8, 0x50, 0xA1, 0x01, 0xB7, 0xD1, 0x82, 0x17, 0x17, 0x17, 0x72, 0x7D,
  0x7D, 0x2D, 0x8D, 0x8D, 0x8D, 0xEA, 0x88, 0x0F, 0x3F, 0x05, 0xCA, 0x19, 0x60, 0x60, 0x60, 0x40, 0x52, 0x53, 0x53, 0xA5, 0xA0, 0xA0, 0xE0, 0x43, 0xE8, 0xED, 0xED, 0xAD, 0x5E, 0x05, 0x74, 0x7A, 0x55, 0x55, 0x95, 0x1A, 0xFD, 0x14, 0x44, 0x40, 0x7A, 0x71,
  0x48, 0x5A, 0x8B, 0x8A, 0x8A, 0x24, 0x3B, 0x3B, 0x5B, 0x0B, 0x8A, 0x6F, 0x0E, 0x61, 0xA1, 0x1E, 0x10, 0xC9, 0xFF, 0x00, 0x02, 0x06, 0x04, 0x5C, 0x98, 0xF8, 0x23, 0xED, 0xAC, 0x69, 0x7B, 0x90, 0x6B, 0x43, 0x61, 0x61, 0xA1, 0x17, 0xF2, 0xFF, 0x80, 0x48,
  0x1A, 0x1A, 0x1A, 0xF4, 0xFC, 0x20, 0xB4, 0x73, 0x76, 0x70, 0x0A, 0x23, 0x9D, 0xCD, 0x3F, 0x81, 0x4B, 0x12, 0x15, 0x56, 0x4D, 0xA8, 0x0A, 0x27, 0xE6, 0xDD, 0x0E, 0x9A, 0x67, 0xF6, 0x62, 0xCF, 0xE0, 0xEE, 0x62, 0x3F, 0x44, 0x76, 0xB6, 0xDE, 0xB5, 0xC2,
  0x15, 0x4E, 0x43, 0xD2, 0x48, 0x56, 0x5D, 0x18, 0x83, 0xF0, 0x42, 0xB0, 0x77, 0x4B, 0x89, 0xBD, 0x93, 0x1A, 0xBB, 0x15, 0xFC, 0xF0, 0x48, 0xE8, 0x8D, 0xAD, 0xAD, 0x2D, 0x2F, 0x02, 0x94, 0x40, 0x86, 0x13, 0x23, 0x33, 0x10, 0x81, 0xD9, 0x59, 0x16, 0x98,
  0x59, 0x47, 0x64, 0x38, 0xBC, 0x9F, 0x96, 0x19, 0x11, 0x11, 0x4E, 0x4D, 0x25, 0xEA, 0xEE, 0xEE, 0xEE, 0x64, 0x6A, 0x6A, 0x4A, 0xFF, 0x7C, 0x80, 0xEA, 0xE9, 0xEE, 0xEE, 0xD6, 0x0A, 0x02, 0x46, 0x88, 0x1D, 0x29, 0xC7, 0x8F, 0x1F, 0x5E, 0x24, 0x00, 0xA7,
  0x54, 0x1B, 0x9B, 0x78, 0x06, 0x9C, 0x09, 0x25, 0x5E, 0x53, 0x53, 0xE3, 0xFD, 0xCC, 0x2A, 0x2B, 0x2B, 0x25, 0x2B, 0x2B, 0xCB, 0x3B, 0x13, 0x43, 0x42, 0x42, 0xC2, 0x17, 0x02, 0xF0, 0x89, 0xE4, 0x3B, 0x64, 0x64, 0x64, 0x68, 0x0A, 0x11, 0x81, 0x33, 0x9C,
  0x33, 0x2C, 0x8A, 0xEF, 0xF0, 0x29, 0x5D, 0xDF, 0x01, 0x67, 0xC7, 0xC7, 0xC7, 0x7A, 0x95, 0x97, 0x94, 0x94, 0x68, 0x1A, 0x39, 0x33, 0x08, 0xFD, 0xD7, 0xFA, 0x57, 0x88, 0xFC, 0x02, 0x51, 0xD5, 0x46, 0xAC, 0x8E, 0xFB, 0x38, 0x5B, 0x00, 0x00, 0x00, 0x00,
  0x49, 0x45, 0x4E, 0x44, 0xAE, 0x42, 0x60, 0x82,
};

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 480, 272, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_0, 181, 19, 141, 29, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "2", ID_BUTTON_0, 194, 61, 50, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "E", ID_BUTTON_1, 310, 169, 50, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "4", ID_BUTTON_2, 135, 115, 50, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "8", ID_BUTTON_3, 195, 170, 50, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "9", ID_BUTTON_4, 251, 170, 50, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "0", ID_BUTTON_5, 310, 61, 50, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "6", ID_BUTTON_6, 252, 115, 50, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "5", ID_BUTTON_7, 194, 115, 50, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "3", ID_BUTTON_8, 252, 61, 50, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "7", ID_BUTTON_9, 134, 170, 50, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "C", ID_BUTTON_10, 311, 116, 50, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "1", ID_BUTTON_11, 135, 59, 50, 50, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "NTUST B10702224", ID_TEXT_0, 119, 230, 265, 35, 0, 0x0, 0 },
  { IMAGE_CreateIndirect, "Image", ID_IMAGE_0, 46, 95, 31, 29, 0, 0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/
/*********************************************************************
*
*       _GetImageById
*/
static const void * _GetImageById(U32 Id, U32 * pSize) {
  switch (Id) {
  case ID_IMAGE_0_IMAGE_0:
    *pSize = sizeof(_acImage_0);
    return (const void *)_acImage_0;
  }
  return NULL;
}

// USER START (Optionally insert additional static code)
extern  WM_HWIN CreateGame(void);
extern int boom_number;
int start;
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  const void * pData;
  WM_HWIN      hItem;
  U32          FileSize;
  int          NCode;
  int          Id;
  // USER START (Optionally insert additional variables)
	uint8_t value[20];
	static char		buffer[20]="5";
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetText(hItem, "5");
    EDIT_SetFont(hItem, GUI_FONT_32_1);
    EDIT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
    //
    // Initialization of 'NTUST B10702224'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_32_1);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FF0000));
    //
    // Initialization of 'Image'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_0);
    pData = _GetImageById(ID_IMAGE_0_IMAGE_0, &FileSize);
    IMAGE_SetPNG(hItem, pData, FileSize);
    // USER START (Optionally insert additional code for further widget initialization)
		boom_number = 5;
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
		sprintf(value,"%s",buffer);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetText(hItem, value);
    switch(Id) {
    case ID_EDIT_0: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_0: // Notifications sent by '2'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
			if(buffer[0] == '0') memset( buffer, '\0', 20 );
			strcat(buffer,"2");
			boom_number = strtod(buffer, NULL);
			
			if(boom_number >99){
				boom_number = 99;
				memset( buffer, '\0', 3 );
				memset( buffer, '9', 2 );
			}
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'E'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				if(boom_number>=5){
					Createplay();
					start=1;
				}
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by '4'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
			if(buffer[0] == '0') memset( buffer, '\0', 20 );
			strcat(buffer,"4");
			boom_number = strtod(buffer, NULL);
			
			if(boom_number >99){
				boom_number = 99;
				memset( buffer, '\0', 3 );
				memset( buffer, '9', 2 );
			}
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by '8'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
			if(buffer[0] == '0') memset( buffer, '\0', 20 );
			strcat(buffer,"8");
			boom_number = strtod(buffer, NULL);
			
			if(boom_number >99){
				boom_number = 99;
				memset( buffer, '\0', 3 );
				memset( buffer, '9', 2 );
			}
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_4: // Notifications sent by '9'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
			if(buffer[0] == '0') memset( buffer, '\0', 20 );
			strcat(buffer,"9");
			boom_number = strtod(buffer, NULL);
			
			if(boom_number >99){
				boom_number = 99;
				memset( buffer, '\0', 3 );
				memset( buffer, '9', 2 );
			}
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_5: // Notifications sent by '0'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
			if(buffer[0] == '0') memset( buffer, '\0', 20 );
			strcat(buffer,"0");
			boom_number = strtod(buffer, NULL);
			
			if(boom_number >99){
				boom_number = 99;
				memset( buffer, '\0', 3 );
				memset( buffer, '9', 2 );
			}
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_6: // Notifications sent by '6'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
			if(buffer[0] == '0') memset( buffer, '\0', 20 );
			strcat(buffer,"6");
			boom_number = strtod(buffer, NULL);
			
			if(boom_number >99){
				boom_number = 99;
				memset( buffer, '\0', 3 );
				memset( buffer, '9', 2 );
			}
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_7: // Notifications sent by '5'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
			if(buffer[0] == '0') memset( buffer, '\0', 20 );
			strcat(buffer,"5");
			boom_number = strtod(buffer, NULL);
			
			if(boom_number >99){
				boom_number = 99;
				memset( buffer, '\0', 3 );
				memset( buffer, '9', 2 );
			}
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_8: // Notifications sent by '3'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
			if(buffer[0] == '0') memset( buffer, '\0', 20 );
			strcat(buffer,"3");
			boom_number = strtod(buffer, NULL);
			
			if(boom_number >99){
				boom_number = 99;
				memset( buffer, '\0', 3 );
				memset( buffer, '9', 2 );
			}
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_9: // Notifications sent by '7'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
			if(buffer[0] == '0') memset( buffer, '\0', 20 );
			strcat(buffer,"7");
			boom_number = strtod(buffer, NULL);
			
			if(boom_number >99){
				boom_number = 99;
				memset( buffer, '\0', 3 );
				memset( buffer, '9', 2 );
			}
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_10: // Notifications sent by 'C'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				memset( buffer, '\0', 20 );
			  memset( buffer, '0', 1 );
				boom_number = 0;
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_11: // Notifications sent by '1'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
			if(buffer[0] == '0') memset( buffer, '\0', 20 );
			strcat(buffer,"1");
			boom_number = strtod(buffer, NULL);
			
			if(boom_number >99){
				boom_number = 99;
				memset( buffer, '\0', 3 );
				memset( buffer, '9', 2 );
			}
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindow(void);
WM_HWIN CreateWindow(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
